# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efEduCAy1AC8W-G0DDkIibnT72tKcedo
"""

!pip install diffusers transformers torch

from diffusers import StableDiffusionPipeline
import torch

# Load the pre-trained model
model_id = "CompVis/stable-diffusion-v1-4"
pipe = StableDiffusionPipeline.from_pretrained(model_id)

# Use CPU for inference
pipe = pipe.to("cpu")

# Define your text prompt
prompt = "A futuristic cityscape with flying cars"

# Generate the image
image = pipe(prompt).images[0]

# Save the image
image.save("generated_image.png")